<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CK.AppIdentity.Hosting" Version="0.14.1" />
    <PackageReference Include="CK.Testing.AspNetServer" Version="21.0.1" />
    <PackageReference Include="CK.Testing.StObjEngine" Version="33.0.2--ci.1" />
    <PackageReference Include="CK.Testing.Nunit" Version="15.0.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.5.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.2.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\CK.AspNet.WebSocketChannel\CK.AspNet.WebSocketChannel.csproj" />
    <ProjectReference Include="..\..\CK.Testing.TypeScriptEngine\CK.Testing.TypeScriptEngine.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="TSInlineTests\" />
  </ItemGroup>
</Project>
