<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CSemVer" Version="13.0.0" />
    <PackageReference Include="CK.ResourceSpace.Assets" Version="0.32.0--ci.4" />
    <PackageReference Include="CK.ResourceSpace.Globalization" Version="0.32.0--ci.4" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CK.ResourceSpace.Transformable\CK.ResourceSpace.Transformable.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="MSBuild\CK.TypeScript.LiveEngine.targets">
      <PackagePath>buildTransitive\CK.TypeScript.LiveEngine.targets</PackagePath>
      <Pack>true</Pack>
    </Content>
  </ItemGroup>
</Project>