<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\CK-TS-JsonGraphSerializer\CK.TS.JsonGraphSerializer\CK.TS.JsonGraphSerializer.csproj" />
    </ItemGroup>
    
</Project>